### ISSUE TITLE
Http request problem

### ISSUE THREAD

**Issue by Pikadili83** [viktorhajer/simple-pdf-viewer#11]
Firstly, thanks for the great library.
I created my own component that uses your pdf library and everything related to pdf works fine. 
But now, all my http requests stopped working. If I remove simple-pdf-viewer from the project, everything works fine. It seems that simple-pdf-viewer sets Response-Type to "text/html;charset=UTF-8" (that's why my interceptor is not triggered anymore).
Am I missing something here?

**Comment by viktorhajer** [comment]
Hello, thanks for the nice words. I tried to find out what can be the problem, but haven't found anything. Maybe the issue in the pdfJS itself (it is used behind the scene as you can see in this repo). There is only a place where I set the responseType which is the openUrl() method, but it is not text/html. Maybe I didn't take you point.

**Comment by viktorhajer** [comment]
Great
