### ISSUE TITLE
Loaded pdf is not cleaned up when new PDF is loaded

### ISSUE THREAD

**Issue by kylewanderson** [viktorhajer/simple-pdf-viewer#14]
When loading a new file, the current pdf is not destroyed, causing lots of memory usage.

loadFile should include a check 
`
if (this.pdf) {
  this.pdf.destroy()
}
`

**Comment by viktorhajer** [comment]
Thx Kyle I will check it later today.

**Comment by viktorhajer** [comment]
Fixed, thank you.
