### ISSUE TITLE
One more memory issue

### ISSUE THREAD

**Issue by kylewanderson** [viktorhajer/simple-pdf-viewer#15]
I'm using the viewer in an app that sometimes shows a pdf and sometimes hides the viewer.

It looks like when the component is destroyed, the PDFDocumentProxy isn't cleaned up. The previous change to destroy the existing pdf on file load looks good, but the follow up would be to add 

```
ngOnDestroy { 
  if(this.pdf) {this.pdf.destroy()}
}
```

**Comment by viktorhajer** [comment]
Hi Kyle! I'm just published the new version with your change. 
Thx!
