### ISSUE TITLE
Failed to load : No 'Access-Control-Allow-Origin' header is present on the requested resource. localhost:4200 is therefore not allowed access..

### ISSUE THREAD

**Issue by alamgirqazi** [viktorhajer/simple-pdf-viewer#17]
I'm getting this error in console. 

`
Failed to load https://www.antennahouse.com/XSLsample/pdf/sample-link_1.pdf: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:4200' is therefore not allowed access. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
`
I'm using 

`
  "@angular/cli": "^1.5.4",
  "@angular/compiler-cli": "5.0.0",
    "simple-pdf-viewer": "^2.0.2",
`

I also got the same error with ng2-pdf-viewer. Maybe the issue is with Angular or Zone.js? 

ng2-pdf-viewer provides `useCredentials: true` options but how to set it here (btw it didn't work for me there either).

**Comment by viktorhajer** [comment]
Check this blog: 
http://restlet.com/company/blog/2015/12/15/understanding-and-using-cors/
