### ISSUE TITLE
Need to show Page Thumbnail

### ISSUE THREAD

**Issue by Vigneshjana** [viktorhajer/simple-pdf-viewer#35]
1. Is it possible to show page thumbnail in this library? If so please explain how to implement that.
2. When we display all the pages and the user click on a specific page i need to get the number of the page ( an event triggered on click) is it possible in this library?

Thanks in advance

**Comment by viktorhajer** [comment]
Sorry, these are not possible with this library - it can show only one page, so single viewer.
