### ISSUE TITLE
NPM Version Control Issue

### ISSUE THREAD

**Issue by nlundby** [viktorhajer/simple-pdf-viewer#4]
|Package|Current|Wanted|Latest|Location|
|---------|--------|---------|------|----------|
|simple-pdf-viewer|1.1.7|1.5.0|1.1.7|xxxx|

Wants a 1.5.0, but 1.1.7 is considered the latest.  When I install 1.5.0, it breaks my build.

**Comment by nlundby** [comment]
Looking at NPM looks like there might have been a typo

1.1.7
1.1.6
1.1.5
1.1.4
1.1.3
1.1.2
1.1.1
1.5.0*
1.1.0
1.0.4
1.0.3
1.0.2
1.0.0

**Comment by viktorhajer** [comment]
Yes, seems to be there were sth problem with the versioning. The history: 
- created: '2018-02-13T16:54:17.727Z',
- '1.0.0': '2018-02-13T16:54:18.850Z',
- '1.0.2': '2018-02-13T17:18:49.687Z',
- '1.0.3': '2018-02-13T17:55:11.028Z',
- '1.0.4': '2018-02-15T17:42:43.974Z',
- '1.5.0': '2018-02-18T10:36:48.069Z',
- '1.1.0': '2018-02-17T10:37:56.063Z',
- '1.1.1': '2018-02-18T12:32:18.750Z' 
- '1.1.2': '2018-02-18T12:45:51.363Z',
- '1.1.3': '2018-02-19T11:34:35.969Z',
- '1.1.4': '2018-02-19T16:29:48.156Z',
- '1.1.5': '2018-02-21T15:34:29.259Z',
- '1.1.6': '2018-02-23T15:59:25.589Z',
- '1.1.7': '2018-02-23T19:47:43.476Z',

So the latest version is the '1.1.7'. 
A gonna release the 2.0.0 in this week to we have clear version.

**Comment by viktorhajer** [comment]
I've released the 2.0.0 version.
