### ISSUE TITLE
Can we have page search instead of search in the whole document.

### ISSUE THREAD

**Issue by arjunr681** [viktorhajer/simple-pdf-viewer#7]
Can we page search instead of search in the whole document.

**Comment by viktorhajer** [comment]
I'm not sure I took your point totally but I would say you can't, because it is not a native windows application. You could only open a PDF file through the file open dialog.

**Comment by viktorhajer** [comment]
As for the searching: 
the PDFFindController of the PDFJs is used for this and I can't see any option to decrease the scope of the searching for the actual page. In theory the search is started at that page, so it may not have a big issue. Also the searching is working in the background, so it is not blocked the other operations. 

Workaround: you can set a flag before the search about the actual page. And if the search navigates to another page you can stop it, and go back... just an idea, there can be more elegant solution. 

Information about the PDF find controller (I may find sth useful here): 
https://github.com/mozilla/pdf.js/blob/be2674a0e8d4bf239e08eb33a42d1f4d15fde7ee/web/pdf_find_controller.js

**Comment by viktorhajer** [comment]
Unfortunately I don't plan to implement this feature because I am not sure that it would be widely used.

**Comment by arjunr681** [comment]
Because i have document which 800 pages. so that i have asked this question. Thanks for guiding me.
