### ISSUE TITLE
Can we give multiple search inputs 

### ISSUE THREAD

**Issue by arjunr681** [viktorhajer/simple-pdf-viewer#8]
I wanted to give multiple search inputs like comma separated values or any other way.  Is there any function in pdfcontroller to do this. 

Multiple words or phrases. Please provide me a solution if any.

**Comment by viktorhajer** [comment]
The third parameter of the search API is the phraseSearch. It may help you.

**Comment by viktorhajer** [comment]
https://github.com/viktorhajer/simple-pdf-viewer/wiki/API-Documentation

**Comment by arjunr681** [comment]
**My pdf paragraph content is following.**

Pdf995
 makes it easy and affordable to create professional-quality documents in the popular PDF file format. Its easy-to-use interface . 

Now if i provide makes affordable as my search input. and i made phrasesearch false.

but it is highlighting only makes.
