### ISSUE TITLE
Scrollable pages

### ISSUE THREAD

**Issue by abbasshujah** [viktorhajer/simple-pdf-viewer#9]
How can I make it display the whole PDF instead of one page at a time, urgent

**Comment by viktorhajer** [comment]
Hi! Unfortunately you can't. In the future I may create option for this but at the moment I try to keep it as simple as possible - so you only can see single page

**Comment by abbasshujah** [comment]
I am not a web developer but I really need that option, I am trying to
create a website and your implementation, Will it be an easy option to
implement?

**Comment by viktorhajer** [comment]
Sorry, but at the moment I do not have capacity to improve in this way the application. 
But you can fork the repo it and implement it yourself.
